import json

from bench import dataset, metrics, report
from bench.contenders import CONTENDERS, MODELS, NAMES


def render(summary: report.Summary, language_report: dict[str, object]) -> str:
    scored = summary.scored
    data = scored.data
    tuned_on = (
        f"the {len(data.ids('dev'))} dev queries"
        if data.suite.primary
        else f"Python's {dataset.DEV_QUERIES} dev queries"
    )
    lines = [
        "# Numbers",
        "",
        (
            f"Generated by `bench score` from `bench/results/`. {data.suite.label}, test queries: "
            f"{len(data.ids('test'))}; thresholds chosen on {tuned_on}: "
            f"jevpipe {scored.thresholds['jevpipe']:.2f}, "
            f"DeepSeek {scored.thresholds['deepseek']:.2f}. "
            "Rows marked * are estimated from a judged sample."
        ),
        "",
        "## Contenders",
        "",
        (
            "| Contender | Found | False hits | Precision | Recall | F1 | Unjudged "
            "| Median s | p90 s | $ / 1k |"
        ),
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for contender in CONTENDERS:
        result = scored.results[contender]
        counts = result.counts
        mark = "*" if contender == "grep-any" else ""
        lines.append(
            f"| {NAMES[contender]}{mark} | {counts.found:,.0f} | {counts.false_hits:,.0f} | "
            f"{counts.precision:.3f} | {counts.recall:.3f} | {counts.f1:.3f} | "
            f"{result.unjudged} | {result.seconds_median:.2f} | {result.seconds_p90:.2f} | "
            f"{result.cost_per_1000:.4f} |"
        )
    lines += _sweep_lines(summary)
    lines += _band_lines(summary)
    lines += ["", "## Judge, misses, repeats", "", "```json"]
    lines += [
        f'"{key}": {json.dumps(language_report[key], ensure_ascii=False)}'
        for key in ("judge", "missed", "repeat", "tally", "spend")
    ]
    lines += ["```"]
    return "\n".join(lines) + "\n"


def _sweep_lines(summary: report.Summary) -> list[str]:
    lines = [
        "",
        "## Thresholds",
        "",
        (
            "| Threshold | jevpipe P | jevpipe R | jevpipe F1 "
            "| DeepSeek P | DeepSeek R | DeepSeek F1 |"
        ),
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    sweeps = [summary.sweeps[model] for model in MODELS]
    for (threshold, jev), (_, other) in zip(*sweeps, strict=True):
        lines.append(
            f"| {threshold:.2f} | {jev.precision:.3f} | {jev.recall:.3f} | {jev.f1:.3f} | "
            f"{other.precision:.3f} | {other.recall:.3f} | {other.f1:.3f} |"
        )
    return lines


def _band_lines(summary: report.Summary) -> list[str]:
    lines = [
        "",
        "## Confidence bands",
        "",
        "Accuracy of the 0.5 decision on labelled pairs, by confidence max(p, 1 - p).",
        "",
        "| Confidence | jevpipe pairs | jevpipe accuracy | DeepSeek pairs | DeepSeek accuracy |",
        "|---|---:|---:|---:|---:|",
    ]
    bands = [summary.bands[model] for model in MODELS]
    for jev, other in zip(*bands, strict=True):
        lines.append(
            f"| {jev.low:.1f}-{jev.high:.1f} | {jev.decisions:,} | {_accuracy(jev)} | "
            f"{other.decisions:,} | {_accuracy(other)} |"
        )
    return lines


def _accuracy(band: metrics.Band) -> str:
    return "-" if band.accuracy is None else f"{band.accuracy:.3f}"
