name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            stage: format,lint,test,deny
          - os: windows-latest
            stage: test
          - os: macos-latest
            stage: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: rustup toolchain install
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
        if: contains(matrix.stage, 'deny')
        with:
          tool: cargo-deny
      - run: ./check.ps1 -Stage ${{ matrix.stage }}
        shell: pwsh

  ci-success:
    needs: check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: test "${{ needs.check.result }}" = success
